### PR TITLE
[udev] allow loading droid firmware blobs via userspace/udev. JB#43076

### PR DESCRIPTION
**Pull request by krnlyng**

### CODE REVIEW

**Comment by Thaodan** [comment]
$@ should be "$@"
See:
https://github.com/koalaman/shellcheck/wiki/SC2068

**Comment by krnlyng** [comment]
@Thaodan updated.

**Comment by Thaodan** [comment]
Also you could add the --priority priority for each message. Should make logs less verbose when needed.

**Comment by Thaodan** [comment]
I think the priority should be daemon.err or daemon.info

**Comment by Thaodan** [comment]
Isn't not finding the firmware an error?

**Comment by krnlyng** [comment]
> Isn't not finding the firmware an error?

in many cases yes but not in every case.

**Pull request merged**
