### PR TITLE
[packaging] Remove bluez-configs from droid-configs.inc. Fixes JB#36529

### PR DESCRIPTION
**Pull request by blammit**
@saukko @lbt bluez-configs is provided by droid-configs.

I don't have access to merge/tag, if you can do this please.

### CODE REVIEW

**Comment by blammit** [comment]
I don't have access to merge/tag this though.

**Comment by saukko** [comment]
I wonder if we should have somekind of comment on line ~40 or so about this or start making some droid-configs.spec.tmpl file that has things like "Provides: bluez-configs" & "Provides: bluez5-configs" etc described?

**Comment by saukko** [comment]
Generally LGTM, however I feel that we should document this a bit.

**Comment by sledges** [comment]
It will break bluetooth on community ports (released targets), unless every porter adds removed lines to their .spec, IIUC

**Comment by saukko** [comment]
Yes, but only when updating the submodule to point to this commit or later. Do you have alternative in mind? I would not do complex macros for such cases as it already has become quite complex in the first place :)

**Comment by lbt** [comment]
I'm trying to recall this - but I think it's worth having a general approach of Provides: bluez-configs-dhc and for bluez-configs to depend on bluez-configs-dhc.
That would allow a way for device specific configs or overrides to be put in here.
The template would have a minimal /no-op

**Comment by sledges** [comment]
Just tested on OnePlus One build - no build-time breakage introduced, after this change it will simply prefer  bluez-configs-mer. Bluetooth on ported devices will break, but at least they are able to build an image.
Instructions on how to bring bluez back (and how to test bluez5) on community ports will follow shortly tomorrow, merging this one, thanks Bea!

**Comment by blammit** [comment]
CC'ing @jpoutiai as well for bluez-configs considerations.

**Pull request merged**
