### PR TITLE
ui: Extend icon_res to include 2.5 pixel ratio and document example

### PR DESCRIPTION
**Pull request by Thaodan**
- [ui] Extend icon_res to include 2.5 pixel ratio and document example. JB#34711

### CODE REVIEW

**Review by llewelld — CHANGES_REQUESTED** [review]
I did a bit more testing locally, but now it seems to only output one of 10, 2.0 or 2.5. The numbers in between (1.25, 1.5, 1.75) are never output, so I think this needs a little more tweaking.

| input | expected output | actual output |
| ----: | ----: | ----: |
| 1.0 | 1.0 | 1.0 |
| 1.25 | 1.25 | 2.0 |
| 1.375 | 1.5 | 2.0 |
| 1.5 | 1.5 | 2.0 |
| 1.75 | 1.75 | 2.0 |
| 2.0 | 2.0 | 2.0 |
| 2.25 | 2.0 | 2.0 |
| 2.375 | 2.5 | 2.0 |
| 2.5 | 2.5 | 2.5 |

**Comment by Thaodan** [comment]
Should be better now.

**Comment by pvuorela** [comment]
I suppose the intention was that >2.25 gets into 2.5? Doesn't work like that now, due to -0.125 subtraction 2.374 onwards the rounding goes to 2.5.

**Comment by Thaodan** [comment]
> I suppose the intention was that >2.25 gets into 2.5? Doesn't work like that now, due to -0.125 subtraction 2.374 onwards the rounding goes to 2.5.

Hm true, removing that subtraction fixes it however I don't know why it was applied originally.

**Comment by pvuorela** [comment]
> Hm true, removing that subtraction fixes it however I don't know why it was applied originally.

Looks like it's there to implement rounding.

**Comment by llewelld** [comment]
Perhaps we could go for something like this, which maintains the rounding, but also makes it easier to add upward steps of 0.5 in the future:

`BEGIN {round=%{pixel_ratio}>2?0.5:0.25;a=int((%{pixel_ratio}+(round/2.0))/round)*round;a=(a<=1?"1.0":(a>=2.5?"2.5":a));print a }`

This translates to:

"if `pixel_ratio` is less than or equal to 2 round to the nearest 0.25; if it's greater than 2 round to the nearest 0.5; bound the result between 1.0 and 2.5 inclusive"

Test output:
```
awk 'BEGIN {for (pixel_ratio = 1.0; pixel_ratio <= 2.5; pixel_ratio += 0.125) { round=pixel_ratio>2?0.5:0.25;a=int((pixel_ratio+(round/2.0))/round)*round;a=(a<=1?"1.0":(a>=2.5?"2.5":a));;print pixel_ratio "\t-> " a }}'
1       -> 1.0
1.125   -> 1.25
1.25    -> 1.25
1.375   -> 1.5
1.5     -> 1.5
1.625   -> 1.75
1.75    -> 1.75
1.875   -> 2
2       -> 2
2.125   -> 2
2.25    -> 2.5
2.375   -> 2.5
2.5     -> 2.5
```

**Comment by llewelld** [comment]
Contrary to my earlier comment, I think it's valid for 2.25 to be rounded to 2.5.

**Pull request merged**
