### PR TITLE
[configs] Add default configurations for bluez4 and obexd.

### PR DESCRIPTION
**Pull request by mlehtima**
In addition to the default configs the commit includes an option to disabled bluetooth.

### CODE REVIEW

**Comment by kimmoli** [comment]
Suggesting to add how-to example in device spec template

    # enable to blabla
    %define use_generic_obexd_configs 1
    %define use_generic_bluez4_configs 1

**Comment by mlehtima** [comment]
The defines were removed so no need to add examples anymore.

**Comment by kimmoli** [comment]
There is `have_no_bluetooth` now

**Comment by mlehtima** [comment]
The define was renamed to remove_bluetooth and also have_modem was renamed to remove_modem. Both are described at the beginning of droid-configs.inc.

**Comment by mkosola** [comment]
:+1:

**Pull request merged**
